name: Auto-add issues to Co Stack

on:
  issues:
    types: [opened, transferred, reopened]

permissions:
  contents: read
  issues: read

jobs:
  add:
    runs-on: ubuntu-latest
    steps:
      - name: Add to user project
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
        run: gh project item-add "3" --owner "rickballard" --url "${{ github.event.issue.html_url }}"
